spring:
  application:
    name: PodAutoScaler
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-user}
    password: ${rabbitmq-password}

namespace: ${NAMESPACE}

defaults:
  minPodCount: 1
  maxPodCount: 10