spring:
  application:
    name: PodAutoScaler
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${RABBITMQ_SERVICE_PORT_AMQP}
    username: ${rabbitmq-user}
    password: ${rabbitmq-password}
    virtual-host: /${rabbitmq-vhost}

namespace: ${NAMESPACE}

defaults:
  minPodCount: 1
  maxPodCount: 9999