spring:
  application:
    name: PodAutoScaler

logging:
  level:
    root: INFO

server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

defaults:
  minPodCount: 1
  maxPodCount: 9999