spring:
  application:
    name: PodAutoScaler
  rabbitmq:
    host: ${pas-rabbitmq-host}
    port: ${pas-rabbitmq-port}
    username: ${pas-rabbitmq-user}
    password: ${rabbitmq-password}

defaults:
  minPodCount: 1
  maxPodCount: 10