apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  config: | {{ .Values.scalerConfig | nindent 4 }}