apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{- include "service.name" . -}}-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{- include "service.name" . -}}-role"
subjects:
  - kind: ServiceAccount
    name: "{{ include "service.serviceAccountName" . }}"